namname: SchoolSphere Auto Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # यह कमांड चेक करेगा कि फाइलें कहाँ हैं (Error ढूंढने के लिए)
      - name: List Files
        run: ls -R

      - name: Get Dependencies
        run: flutter pub get
        # अगर आपकी फाइलें अभी भी किसी फोल्डर में हैं, तो यहाँ 'working-directory: फोल्डर_का_नाम' जोड़ें

      - name: Build Web
        run: flutter build web --base-href "/school-management-app1/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web 
          branch: gh-pages
